server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webchat?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

mybatis-plus:
  type-aliases-package: com.afk.pojo
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true